name: Build Application

on:
  push:
    tags:
      - "*"

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller app.spec
      - name: ZIP Release Package
        run: |
          7z a YGO-Card-Lookup.zip dist/* -r
      - name: Debug Directory Structure
        run: ls -R
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "YGO-Card-Lookup.zip"